image: gradle:5.5-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - docker
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./deploy/bump-gitlab-version.sh
    - ./gradlew --build-cache remoteK8s
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script: ./gradlew check

docker:
  stage: docker
  image: docker:18
  services:
    - docker:dind
  script:
    - ./deploy/docker-build-push.sh


