image: gradle:5.5-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - docker
  - deploy


cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./deploy/bump-gitlab-version-tag.sh
    - ./gradlew --build-cache remoteK8s
  artifacts:
    paths:
      - build/libs/*.jar
      - build/deployment.yml
      - build/generated-resources/version.config
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script: ./gradlew check

docker:
  stage: docker
  image: docker:18
  services:
    - docker:dind
  script:
    - ./deploy/docker-build-push.sh

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - kubectl apply -f build/deployment.yml

