kind: Service
apiVersion: v1
metadata:
  name: hello-ng-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: hello-ng
  ports:
    - port: 80
      targetPort: 5000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-ng
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: hello-ng
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hello-ng
    spec:
      containers:
        - name: hello-ng
          image: ${REGISTRY}/springville/hello-ng:${VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
            requests:
              memory: "100Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /healthy
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3